#ifndef __MODBUS_H_36A59180_48D8_416f_921F_64BE48FFECB5
#define __MODBUS_H_36A59180_48D8_416f_921F_64BE48FFECB5

#include "App.h"
#include "ModbusOpts.h"
#include "ModbusOptsCal.h"

typedef enum
{
	ILLEGAL_FUNCTION = 1,
	ILLEGAL_DATA_ADDRESS = 2,
	ILLEGAL_DATA_VALUE = 3,
	SLAVE_DEVICE_FAILURE = 4,
	ACKNOWLEDGE = 5,
	SLAVE_DEVICE_BUSY = 6,
	MEMORY_PARITY_ERROR = 7,
	GATEWAY_PATH_UNAVAILABLE = 0xA,
	GATEWAY_TARGET_DEVICE_FAILED_TO_RESPOND = 0xB,
        WRITE_ACCESS_DENIED = 20,
}MODBUSEXCEPTION;

typedef enum
{
	BASIC_IDENTIFICATION = 1,
	REGULAR_IDENTIFICATION = 2,
	EXTENDED_IDENTIFICATION = 3,
	SPECIFIC_IDENTIFICATION_OBJECT = 4,
}MODBUSREADDEVICEIDCODE;

typedef enum
{
	//BIT ACCESS
	READ_DISCRETE_INPUTS = 2,
	READ_COILS = 1,
	WRITE_SINGLE_COIL = 5,
	WRITE_MULTIPLE_COILS = 15,

	//16 BITS ACCESS
	READ_INPUT_REGISTER = 4,
	READ_HOLDING_REGISTERS = 3,
	WRITE_SINGLE_REGISTER = 6,
	WRITE_MULTIPLE_REGISTERS = 16,
	READWRITE_MULTIPLE_REGISTERS = 23,
	MASK_WRITE_REGISTER = 22,

	READ_FILE_RECORD = 20,
	WRITE_FILE_RECORD = 21,
	//DIAGNOSTICS
	REPORT_SLAVE_ID = 17,
	READ_DEVICE_IDENTIFICATION = 43,

	//User Defined - 65
	MEKI_DEVICE_INFO = 65,
	MEKI_SET_FUNCTION_BLOCK = 66,
	MEKI_SET_TEMPTABLE_TYPE = 67,
	MEKI_GET_FUNCTION_BLOCK = 68,
	MEKI_GET_TEMPTABLE_TYPE = 69,
	MEKI_SET_FUNCTION_BLOCK_DATA = 70,	//YIN 3.0
	MEKI_GET_FUNCTION_BLOCK_DATA = 71,

    //User Defined - 100
    MEKI_SET_FUNCTION_BLOCK_V3 = 100, //vincent 20220714 FB V3.0
	MEKI_GET_FUNCTION_BLOCK_V3 = 101,
    MEKI_SET_FUNCTION_BLOCK_DATA_V3 = 102, 	
	MEKI_GET_FUNCTION_BLOCK_DATA_V3 = 103,
    MEKI_FUNCTION_BLOCK_V3 = 104,
	MEKI_PASSTHROUGH = 105, //vincent 20220923 pass to IO Modules (FW Upgrade, etc.)

	SEDONA_FRAME = 108,
	MEKI_CUSTOME_FUNCTION = 110,
	MEKI_FUNCTION_BLOCK = 111,
	MEKI_TEMPTABLE_TYPE = 112,
	MEKI_KXD_WRITEINFO = 113,
    MEKI_KXD_READINFO = 114,
}MODBUSFUNCTION;
#endif	/* end of __MODBUS_H_36A59180_48D8_416f_921F_64BE48FFECB5 */
